/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PlantService } from "../plant.service";
import { PlantCreateInput } from "./PlantCreateInput";
import { Plant } from "./Plant";
import { PlantFindManyArgs } from "./PlantFindManyArgs";
import { PlantWhereUniqueInput } from "./PlantWhereUniqueInput";
import { PlantUpdateInput } from "./PlantUpdateInput";
import { DeviceFindManyArgs } from "../../device/base/DeviceFindManyArgs";
import { Device } from "../../device/base/Device";
import { DeviceWhereUniqueInput } from "../../device/base/DeviceWhereUniqueInput";

export class PlantControllerBase {
  constructor(protected readonly service: PlantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Plant })
  async createPlant(@common.Body() data: PlantCreateInput): Promise<Plant> {
    return await this.service.createPlant({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        refId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Plant] })
  @ApiNestedQuery(PlantFindManyArgs)
  async plants(@common.Req() request: Request): Promise<Plant[]> {
    const args = plainToClass(PlantFindManyArgs, request.query);
    return this.service.plants({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        refId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Plant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async plant(
    @common.Param() params: PlantWhereUniqueInput
  ): Promise<Plant | null> {
    const result = await this.service.plant({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        refId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Plant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePlant(
    @common.Param() params: PlantWhereUniqueInput,
    @common.Body() data: PlantUpdateInput
  ): Promise<Plant | null> {
    try {
      return await this.service.updatePlant({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          refId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Plant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePlant(
    @common.Param() params: PlantWhereUniqueInput
  ): Promise<Plant | null> {
    try {
      return await this.service.deletePlant({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          refId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/devices")
  @ApiNestedQuery(DeviceFindManyArgs)
  async findDevices(
    @common.Req() request: Request,
    @common.Param() params: PlantWhereUniqueInput
  ): Promise<Device[]> {
    const query = plainToClass(DeviceFindManyArgs, request.query);
    const results = await this.service.findDevices(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/devices")
  async connectDevices(
    @common.Param() params: PlantWhereUniqueInput,
    @common.Body() body: DeviceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      devices: {
        connect: body,
      },
    };
    await this.service.updatePlant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/devices")
  async updateDevices(
    @common.Param() params: PlantWhereUniqueInput,
    @common.Body() body: DeviceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      devices: {
        set: body,
      },
    };
    await this.service.updatePlant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/devices")
  async disconnectDevices(
    @common.Param() params: PlantWhereUniqueInput,
    @common.Body() body: DeviceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      devices: {
        disconnect: body,
      },
    };
    await this.service.updatePlant({
      where: params,
      data,
      select: { id: true },
    });
  }
}
